os:
  - osx
language: c
compilers:
  - clang
  - gcc
before_install:
  - env
  - brew update
  - brew upgrade
  - brew tap leedm777/homebrew-asterisk
  - brew ls
install:
  - brew install --only-dependencies ./asterisk.rb
script:
  # Current version
  - brew install ./asterisk.rb --verbose --with-dev-mode --with-${CC}
  # Current release branch
  - brew install ./asterisk.rb --verbose --with-dev-mode --devel --with-${CC}
  # Next release branch
  - brew install ./asterisk.rb --verbose --with-dev-mode --HEAD --with-${CC}
