language: c
os:
  - osx
env:
  matrix:
    - CLANG=--with-clang
    - CLANG=
before_install:
  - env
  - brew update
  - brew upgrade
  - brew ls
install:
  - brew tap leedm777/homebrew-asterisk
script:
  # The explicit CC= is b/c Travis CI sets it to gcc, which is gcc-4.2
  # Current version
  - CC= brew install ./asterisk.rb --verbose --with-dev-mode ${CLANG}
  # Current release branch
  - CC= brew install ./asterisk.rb --verbose --with-dev-mode --devel ${CLANG}
  # Next release branch
  - CC= brew install ./asterisk.rb --verbose --with-dev-mode --HEAD ${CLANG}
