os:
  - osx
language: c
compilers:
  - clang
  - gcc
env:
  - EXTRA=
  - EXTRA=--devel
  - EXTRA=--HEAD
before_install:
  - env
  - brew update
  - brew upgrade
  - brew tap leedm777/homebrew-asterisk
  - brew ls
install:
  - brew install --only-dependencies ./asterisk.rb
script:
  - brew reinstall ./asterisk.rb --verbose --with-dev-mode --with-${CC} ${EXTRA}
