os:
  - osx
osx_image: xcode7.3
language: c
compiler:
  - clang
  - gcc
env:
  - EXTRA=
  - EXTRA=--devel
  - EXTRA=--HEAD
  - EXTRA="--devel --with-dev-mode"
  - EXTRA="--HEAD --with-dev-mode"
before_install:
  - env
  - brew update
  - brew tap leedm777/homebrew-asterisk
  # manually tap versions so brew deps will work
  - brew tap homebrew/versions
  # upgrade only outdated dependencies
  - comm -12 <(brew deps ./asterisk.rb) <(brew outdated) | xargs brew upgrade
  - brew ls
install:
  # install pjsip verbosely, in case we need to debug that build, too
  # We also have to install it via the tap, b/c it won't be picked up as a
  # dependency if we install it as ./pjsip-asterisk.rb
  - brew install pjsip-asterisk --verbose
  - brew install --only-dependencies ./asterisk.rb
script:
  - brew reinstall ./asterisk.rb --verbose --with-dev-mode --with-${CC} ${EXTRA}
